### ISSUE TITLE
Deeper explanation on why using Azure ACR

### ISSUE THREAD

**Issue by stijnmoreels** [invictus-integration/docs-ifa#156]
**Is your feature related to a problem? Please describe.**
Currently, after the Helm deploy, we provide a suggestion to do 'something' with Azure ACR, but the purpose or reason for this is not explained.

**What solution do you propose?**
We should make sure that after the Helm deploy, we provide more info on why to use Azure ACR. I'm guessing it is to more easily manage future deployments on on-premise machines? A clear explanation on this and a visual confirmation of such deployment result would be helpful.

**Comment by stijnmoreels** [comment]
Maybe an idea to more link to the [Azure documentation](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli%2Cazure-cloud) for Azure ACR instead of trying replicate the commands in a `./arc.ps1` file.

**Comment by GoutsmitSam** [comment]
@stijnmoreels While your comment surely has merit, at the moment the path to support Hybrid scenario's with Invictus is not active anymore, at least until Microsoft puts some more work into Azure Arc. Since in the future, we'll have to rework the Hybrid scenario once it becomes relevant again, I'll close this issue now.

**Comment by stijnmoreels** [comment]
Ok! 👍
