### ISSUE TITLE
To investigate: should we use Application Insights for Logic Apps standard?

### ISSUE THREAD

**Issue by GoutsmitSam** [invictus-integration/docs-ifa#233]
**Is your feature request related to a problem? Please describe.**
Currently we are ingesting diagnostic data through the Event Hub, but this can be quite costly.

**Describe the solution you'd like**
For Logic Apps Standard, using Application Insights directly is now possible, so should we consider getting our diagnostic data directly from Application Insights instead of Event Hub (for LA Standard)

At the very least, it can be a potential cost-saver for our clients.

https://learn.microsoft.com/en-us/azure/logic-apps/enable-enhanced-telemetry-standard-workflows?tabs=portal
https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=net

**Additional context**
As long as we still support Consumption and Standard Logic Apps, we would need to maintain two different systems.

**Comment by pim-simons** [comment]
From my experience using Application Insights combined with Logic App Standard is very expensive, as a huge amount of logging is sent to Application Insights, the more Logic Apps you have, the more logging. At multiple customers we have set a daily cap for the Logic App Standard Logging because customers started complaining about the cost of OMS and Application Insights (that daily cap is reached in about 30 mins 😉) and they don't really use or look at it anyway. 

Next to that, Application Insights uses sampling, which means that some logging might get lost. 

So from my point of view Application Insights would not be a very good fit here.
